anszlus_stempel_integracja_ism:
    path: /stempel/integracja-ism
    defaults:
        _controller: anszlus.stempel.controller.stempel_controller:integracja_ism

anszlus_stempel_integracja_nowiny:
    path: /stempel/integracja-nowiny
    defaults:
        _controller: anszlus.stempel.controller.stempel_controller:integracja_nowiny

anszlus_stempel_integracja_muk:
    path: /stempel/integracja-muk
    defaults:
        _controller: anszlus.stempel.controller.stempel_controller:integracja_muk

anszlus_stempel_verification:
    path: /stempel/weryfikacja
    defaults:
        _controller: anszlus.stempel.controller.stempel_controller:stempel_verification

anszlus_stempel_version:
    path: /stempel/version
    defaults:
        _controller: anszlus.stempel.controller.stempel_controller:version